#!usr/bin/env bash
# This script pings an IP address passed as an argument.

ping_count(){
	ping -c -1 "$i" | grep -c bytes
}

for ip in "$i";

	do
		if [[ $(ping_count "$ip") -gt 1]]
		then
			echo "The IP address $ip pings"
		else
			echo "The IP address $ip doesn't ping"
		fi
	done
