#!/usr/bin/env bash
# prints "To infinity and beyond" indefinitely
# with a sleep 2 in between each iteration and 
# print "I am invincible!!" when SIGTERM signal is recieved

trap "echo 'I am invincible!!!'" SIGTERM
while :; do echo 'To infinity and beyond'; sleep 2; done
