#!/usr/bin/env bash
#This script is displaying "Best School" 10 times.

i=1
while [ $i -le 8 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 7 ]
	then
		echo "bad luck"
	fi
	echo "Best School"
	((i++))
done
