#!/usr/bin/env bash
#This prints numbers 1 to 20 except 4, 9 and 17.
#prints "bad luck from china" for 4th iteration.
#prints "bad luck from Japan" for 9th iteration.
#prints "bad luck from Italy" for 17th iteration.

i=1
while [ $i -le 20 ]
do
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	echo "$i"
	((i++))
done
